apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"

    exporters:
      # 新增 Prometheus exporter，设置一个供 Prometheus 抓取的端口（例如 9464）
      prometheus:
        endpoint: "0.0.0.0:9464"
      debug: {}  # 可选，用于调试日志

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          # 将原来 debug 改成 prometheus exporter
          exporters: [prometheus]
      telemetry:
        metrics:
          address: "0.0.0.0:8890"
