apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: default
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: prometheus
    port: 9464
    targetPort: 9464
  selector:
    app: otel-collector
