apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: compose-post-service-vpa
  namespace: social-network
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compose-post-service
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 50m
        memory: 128Mi
      maxAllowed:
        cpu: 400m
        memory: 512Mi