apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cpu-controller-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cpu-controller-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cpu-controller-binding
subjects:
- kind: ServiceAccount
  name: k8s-cpu-controller-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-cpu-controller-role
  apiGroup: rbac.authorization.k8s.io