apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-system
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'otel-collector'
      static_configs:
        - targets: ['otel-collector.default.svc.cluster.local:9464']
    - job_name: 'kubelet-cadvisor'
      scrape_timeout: 20s 
      scheme: https
      metrics_path: /metrics/cadvisor
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - source_labels: [__address__]
          regex: '(.*):10250'
          target_label: __address__
          replacement: '$1:10250'
      # 这里对采集到的指标做二次 relabel，提取出 deployment 名称，并只保留指定的
      metric_relabel_configs:
      - source_labels: [pod]
        regex: '^(.+)-[^-]+-[^-]+$'
        target_label: deployment
        replacement: '$1'
