apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: compose-post-service
  name: compose-post-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      service: compose-post-service
  template:
    metadata:
      labels:
        service: compose-post-service
        app: compose-post-service
    spec:
      containers:
      - name: compose-post-service
        image: docker.io/airis03/social-network:latest
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 9090
        - containerPort: 9464
        command:
        - ComposePostService
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: compose-post-service-config
          mountPath: /config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: compose-post-service-config
          mountPath: /config/service-config.json
          subPath: service-config.json
      volumes:
      - name: compose-post-service-config
        configMap:
          name: compose-post-service
      hostname: compose-post-service
      restartPolicy: Always
