apiVersion: v1
kind: Service
metadata:
  name: home-timeline-redis
  namespace: social-network
spec:
  type: ClusterIP
  ports:
  - name: '6379'
    port: 6379
    targetPort: 6379
  - name: '9464'
    port: 9464
    targetPort: 9464
  selector:
    service: home-timeline-redis
