apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: home-timeline-redis
  name: home-timeline-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      service: home-timeline-redis
  template:
    metadata:
      labels:
        service: home-timeline-redis
        app: home-timeline-redis
    spec:
      containers:
      - name: home-timeline-redis
        image: docker.io/library/redis:6.2.4
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        - containerPort: 9464
        args:
        - /config/redis.conf
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: home-timeline-redis-config
          mountPath: /config/redis.conf
          subPath: redis.conf
      volumes:
      - name: home-timeline-redis-config
        configMap:
          name: home-timeline-redis
      hostname: home-timeline-redis
      restartPolicy: Always
