apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: media-service
  name: media-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      service: media-service
  template:
    metadata:
      labels:
        service: media-service
        app: media-service
    spec:
      containers:
      - name: media-service
        image: docker.io/airis03/social-network:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        - containerPort: 9464
        command:
        - MediaService
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: media-service-config
          mountPath: /config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: media-service-config
          mountPath: /config/service-config.json
          subPath: service-config.json
      volumes:
      - name: media-service-config
        configMap:
          name: media-service
      hostname: media-service
      restartPolicy: Always
