apiVersion: v1
kind: Service
metadata:
  name: media-frontend
  namespace: social-network
spec:
  type: ClusterIP
  ports:
  - name: '8081'
    port: 8081
    targetPort: 8080
  - name: '9464'
    port: 9464
    targetPort: 9464
  selector:
    service: media-frontend
