apiVersion: v1
kind: Service
metadata:
  name: nginx-thrift
  namespace: social-network
spec:
  type: NodePort
  ports:
  - name: '8080'
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: '9464'
    port: 9464
    targetPort: 9464
  selector:
    service: nginx-thrift
