apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-social-network
  labels:
    type: local
  namespace: social-network
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /DeathStarBench
