apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-social-network
  namespace: social-network
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
