apiVersion: v1
kind: Service
metadata:
  name: social-graph-service
  namespace: social-network
spec:
  type: ClusterIP
  ports:
  - name: '9090'
    port: 9090
    targetPort: 9090
  - name: '9464'
    port: 9464
    targetPort: 9464
  selector:
    service: social-graph-service
