apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: text-service
  name: text-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      service: text-service
  template:
    metadata:
      labels:
        service: text-service
        app: text-service
    spec:
      containers:
      - name: text-service
        image: docker.io/airis03/social-network:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        - containerPort: 9464
        command:
        - TextService
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: text-service-config
          mountPath: /config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: text-service-config
          mountPath: /config/service-config.json
          subPath: service-config.json
      volumes:
      - name: text-service-config
        configMap:
          name: text-service
      hostname: text-service
      restartPolicy: Always
