apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: url-shorten-memcached
  name: url-shorten-memcached
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      service: url-shorten-memcached
  template:
    metadata:
      labels:
        service: url-shorten-memcached
        app: url-shorten-memcached
    spec:
      containers:
      - name: url-shorten-memcached
        image: docker.io/library/memcached:1.6.7
        imagePullPolicy: Always
        ports:
        - containerPort: 11211
        - containerPort: 9464
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: url-shorten-memcached-config
          mountPath: /config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: url-shorten-memcached-config
          mountPath: /config/service-config.json
          subPath: service-config.json
      volumes:
      - name: url-shorten-memcached-config
        configMap:
          name: url-shorten-memcached
      hostname: url-shorten-memcached
      restartPolicy: Always
