---
# Source: social-network/charts/nginx-thrift/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: nginx-thrift
  name: nginx-thrift
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: nginx-thrift
  template:
    metadata:
      labels:
        service: nginx-thrift
        app: nginx-thrift
    spec: 
      containers:
      - name: "nginx-thrift"
        image: docker.io/yg397/openresty-thrift:xenial
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 9464
        env:
        - name: fqdn_suffix
          value: ".social-network.svc.cluster.local"
          
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi        
        volumeMounts:
        - name: nginx-thrift-config
          mountPath: /usr/local/openresty/nginx/jaeger-config.json
          subPath: jaeger-config.json
        - name: nginx-thrift-config
          mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
        - name: lua-scripts
          mountPath: /usr/local/openresty/nginx/lua-scripts
        - name: lua-thrift
          mountPath: /usr/local/openresty/lualib/thrift
        - name: pages
          mountPath: /usr/local/openresty/nginx/pages
        - name: gen-lua
          mountPath: /gen-lua
        - name: keys
          mountPath: /keys

      initContainers:
      - name: "alpine-container"
        image: docker.io/alpine/git:latest
        imagePullPolicy: Always
        command: 
        - /bin/sh
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        args:
        - -c
        - cp -r /DeathStarBench/socialNetwork/gen-lua/* /gen-lua/ && cp -r /DeathStarBench/socialNetwork/docker/openresty-thrift/lua-thrift/* /lua-thrift/ && cp -r /DeathStarBench/socialNetwork/nginx-web-server/lua-scripts/* /lua-scripts/ && cp -r /DeathStarBench/socialNetwork/nginx-web-server/pages/* /pages/ && cp /DeathStarBench/socialNetwork/keys/* /keys/         
        volumeMounts:
        - name: lua-scripts
          mountPath: /lua-scripts
        - name: lua-thrift
          mountPath: /lua-thrift
        - name: pages
          mountPath: /pages
        - name: gen-lua
          mountPath: /gen-lua
        - name: keys
          mountPath: /keys
        - name: pv-social-network
          mountPath: /DeathStarBench
      volumes:
      - name: nginx-thrift-config
        configMap:
          name: nginx-thrift
      - name: lua-scripts
        emptyDir: {}
      - name: pages
        emptyDir: {}
      - name: gen-lua
        emptyDir: {}
      - name: lua-thrift
        emptyDir: {}
      - name: keys
        emptyDir: {}
      - name: pv-social-network
        persistentVolumeClaim:
          claimName: pvc-social-network
      hostname: nginx-thrift
      restartPolicy: Always
