---
# Source: social-network/charts/post-storage-mongodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: post-storage-mongodb
  name: post-storage-mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: post-storage-mongodb
  template:
    metadata:
      labels:
        service: post-storage-mongodb
        app: post-storage-mongodb
    spec:
      containers:
      - name: "post-storage-mongodb"
        image: docker.io/library/mongo:4.4.6
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        - containerPort: 9464
        args:
        - --config
        - /config/mongod.conf           
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi        
        volumeMounts:
        - name: post-storage-mongodb-config
          mountPath: /config/mongod.conf
          subPath: mongod.conf
      volumes:
      - name: post-storage-mongodb-config
        configMap:
          name: post-storage-mongodb
      hostname: post-storage-mongodb
      restartPolicy: Always
