---
# Source: social-network/charts/post-storage-memcached/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: post-storage-memcached
  name: post-storage-memcached
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: post-storage-memcached
  template:
    metadata:
      labels:
        service: post-storage-memcached
        app: post-storage-memcached
    spec:
      containers:
      - name: "post-storage-memcached"
        image: docker.io/library/memcached:1.6.7
        imagePullPolicy: Always
        ports:
        - containerPort: 11211
        - containerPort: 9464           
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi        
        volumeMounts:
        - name: post-storage-memcached-config
          mountPath: /config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: post-storage-memcached-config
          mountPath: /config/service-config.json
          subPath: service-config.json
      volumes:
      - name: post-storage-memcached-config
        configMap:
          name: post-storage-memcached
      hostname: post-storage-memcached
      restartPolicy: Always
