---
# Source: social-network/charts/social-graph-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: social-graph-service
  name: social-graph-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: social-graph-service
  template:
    metadata:
      labels:
        service: social-graph-service
        app: social-graph-service
    spec:
      containers:
      - name: "social-graph-service"
        image: docker.io/fenglin02/social-network:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        - containerPort: 9464
        command: 
        - SocialGraphService           
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi        
        volumeMounts:
        - name: social-graph-service-config
          mountPath: /config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: social-graph-service-config
          mountPath: /config/service-config.json
          subPath: service-config.json
      volumes:
      - name: social-graph-service-config
        configMap:
          name: social-graph-service
      hostname: social-graph-service
      restartPolicy: Always
