---
# Source: social-network/charts/social-graph-redis/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: social-graph-redis
  name: social-graph-redis
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: social-graph-redis
  template:
    metadata:
      labels:
        service: social-graph-redis
        app: social-graph-redis
    spec:
      containers:
      - name: "social-graph-redis"
        image: docker.io/library/redis:6.2.4
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        - containerPort: 9464
        args:
        - /config/redis.conf           
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi        
        volumeMounts:
        - name: social-graph-redis-config
          mountPath: /config/redis.conf
          subPath: redis.conf
      volumes:
      - name: social-graph-redis-config
        configMap:
          name: social-graph-redis
      hostname: social-graph-redis
      restartPolicy: Always
