---
# Source: social-network/charts/social-graph-redis/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: social-graph-redis
spec:
  type: ClusterIP
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  - name: "9464"
    port: 9464
    targetPort: 9464
  selector:
    service: social-graph-redis
