---
# Source: social-network/charts/unique-id-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: unique-id-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  - name: "9464"
    port: 9464
    targetPort: 9464
  selector:
    service: unique-id-service
