---
# Source: social-network/charts/user-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  - name: "9464"
    port: 9464
    targetPort: 9464
  selector:
    service: user-mongodb
